export devhome=$HOME/git/
alias dh="cd $devhome && pwd"

# Backlight
# clone, make, and make install from the following repository
# https://github.com/haikarainen/light.git
# light -A 10 // increase backlight by 10
# light -U 10 // decrease backlight by 10

# Bashrc
alias reload="source ~/.bashrc"
alias bashrc="vi ~/.bash_aliases && reload"

# Find
alias ff="find . -name $1"

# Git
alias gits="git status --short"

# I3
alias i3config="vi ~/.config/i3/config"

# Navigation
alias lrt="ls -lrt"
alias lart="ls -lart"
alias c="clear"

# Programs
alias eclipse="eclipse &"
alias grep="grep --color"
alias go="gnome-open"
alias psg="ps -ef | grep"
alias term="gnome-terminal &"
alias firefox="firefox &"

# Scratch
alias scratch="cd ~/scratch && ~/.userscripts/CreateUniqueScratchCpp.sh"

# Todo
alias todo="vi ~/.todo"

# Vim
alias vim="vim -p"
alias vimrc="vi ~/.vimrc"

# Vim Dev
function flist  { find ~/git/RTSTF -iname '*.cpp' -o -iname '*.cc' -o -iname '*.c' -o -iname '*.hpp' -o -iname '*.hh' -o -iname '*.h' ; }
function mlist  { find ~/git/RTSTF -iname 'makefile' ; }
function mktags { 'cd ~/git/ && flist > cscope.files && ctags -L cscope.files && cscope -bqv' ; }
alias vv='(mktags && cd ~/git/ &&  vim)'

# Volume
alias setvol="amixer set Master $1"
